version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.0
jobs:
  buscar_s3:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run: |
            aws s3 cp s3://testcduartebucket/especificacion_delivery_pipeline.txt delivery_pipeline/especificacion_delivery_pipeline.txt
      - run:
          name: Permission to especificacion_delivery_pipeline.txt
          command: chmod +x delivery_pipeline/especificacion_delivery_pipeline.txt
      - run: ls -lha delivery_pipeline
      - run: ls -lha .circleci/delivery_pipeline
      - run: cat .circleci/delivery_pipeline/especificacion_delivery_pipeline.txt
      - run: delivery_pipeline/especificacion_delivery_pipeline.txt
      - run: diff -r -q '.circleci/delivery_pipeline/especificacion_delivery_pipeline.txt' 'delivery_pipeline/especificacion_delivery_pipeline.txt'
          
workflows:
  aws-cli:
    jobs:
      - buscar_s3

