version: 2.1


orbs:
  aws-cli: circleci/aws-cli@4.0.0


# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  test_delivery_pipeline:
    steps:
      - checkout
      - aws-cli/setup


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
