version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.0
jobs:
  configure_role_arn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run: >-
          aws sts assume-role --role_arn
          "arn:aws:iam::123456789012:role/example-role" --role_session_name
          AWSCLI-Session
workflows:
  aws-cli:
    jobs:
      - configure_role_arn
