version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.0
jobs:
  buscar_s3:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run: |
            aws s3 cp s3://testcduartebucket/especificacion_delivery_pipeline.txt especificacion_delivery_pipeline.txt 
      - run: ls -lha
  mostar_s3:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: cat especificacion_delivery_pipeline.txt 
          
workflows:
  aws-cli:
    jobs:
      - buscar_s3
      - mostar_s3:
        requires:
          - buscar_s3
