version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.0
jobs:
  buscar_s3:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run: |
            aws s3 cp s3://testcduartebucket/especificacion_delivery_pipeline.txt delivery_pipeline/especificacion_delivery_pipeline.txt 
      - run: ls -lha
      - run: ls -lha .circleci
      - run: diff -r -q '.circleci/delivery_pipeline/especificacion_delivery_pipeline.txt' 'delivery_pipeline/especificacion_delivery_pipeline.txt'
          
workflows:
  aws-cli:
    jobs:
      - buscar_s3

