version: 2.1


orbs:
  aws-cli: circleci/aws-cli@4.0.0

commands:
  obtener_s3:
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Obtener s3
          command: |
            aws s3 cp s3://testcduartebucket/especificacion_delivery_pipeline.txt
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
